trigger:
- main

variables:
  appDir: client

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
  
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(appDir)'
  displayName: npm install

- script: npm start
  workingDirectory: $(appDir)
  displayName: npm build


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (ca94896a-2ad6-4c15-998f-06a093ec4590)'
    appType: 'webAppLinux'
    WebAppName: 'spotterfly'
    packageForLinux: '$(appDir)/dist/*'